public class Ques5 {
    public static void main(String[] args) {

        Student s1 = new Student(1, "Sakshi", 22);
        Student s2 = new Student(1, "Sakshi", 22);
        Student s3 = new Student(2, "Aman", 23);

        // Using equals() (auto-generated by record)
        System.out.println("s1 equals s2: " + s1.equals(s2)); // true
        System.out.println("s1 equals s3: " + s1.equals(s3)); // false

        // Accessing record components
        System.out.println(s1.name());
        System.out.println(s1.id());
        System.out.println(s1.age());

        // Static counter
        System.out.println("Total Student objects created: " + Student.getCount());
    }
}

/*  RECORD */

record Student(int id, String name, int age) {


    private static int count = 0;

    // Canonical constructor
    public Student {
        if (id <= 0)
            throw new IllegalArgumentException("Id must be positive");

        if (age <= 0)
            throw new IllegalArgumentException("Age must be positive");

        if (name == null || name.isBlank())
            throw new IllegalArgumentException("Name cannot be blank");

        // increment counter whenever object is created
        count++;
    }

    // static method to access counter
    public static int getCount() {
        return count;
    }
}
